language: python
python:
- 2.7
- 3.4
- 3.6
cache:
- pip
install:
- pip install --upgrade pip
- pip install -r test-requirements.txt -e .
script:
- pytest --cov escapism tests
after_success:
- codecov

